install: |-
  sudo apt-get install -y ruby ruby-dev
  sudo apt-get install -y libmagic-dev
  sudo apt-get install -y bsdmainutils
  sudo gem update
architect:
  - LeanderK
  - jundl77
decrypt:
  settings.xml: "repo/settings.xml.asc"
  pubring.gpg: "repo/pubring.gpg.asc"
  secring.gpg: "repo/secring.gpg.asc"
docker:
  image: "teamed/docker-java-8"
release:
  commanders:
      - LeanderK
      - jundl77
  script: |-
    gem install --no-ri --no-rdoc pdd
    gem install est
    gem install pdd
    gem install nokogiri
    mvn versions:set "-DnewVersion=${tag//\'}"
    git commit -am "${tag//\'}"
    mvn -Dmaven.test.skip=true clean deploy --settings /home/r/settings.xml
