install: |-
  sudo apt-get install -y libmagic-dev zlib1g-dev
  sudo apt-get update
  sudo apt-get install -y ruby ruby-dev
  sudo apt-get install -y libmagic-dev
  sudo apt-get install -y bsdmainutils
  sudo gem update && gem install nokogiri && gem install bundler
#  sudo gem update
#  sudo gem install --no-ri --no-rdoc pdd
#  sudo gem install est
#  sudo gem install pdd
#  sudo gem install nokogiri
architect:
  - LeanderK
  - jundl77
decrypt:
  settings.xml: "repo/settings.xml.asc"
  pubring.gpg: "repo/pubring.gpg.asc"
  secring.gpg: "repo/secring.gpg.asc"
docker:
  image: "teamed/docker-java-8"
release:
  commanders:
      - LeanderK
      - jundl77
  script: |-
    mvn versions:set "-DnewVersion=${tag//\'}"
    git commit -am "${tag//\'}"
    mvn -Dmaven.test.skip=true clean deploy --settings /home/r/settings.xml
