install: |-
  sudo apt-get install -y ruby ruby-dev
  sudo apt-get install -y libmagic-dev
  sudo apt-get install -y bsdmainutils
  sudo apt-get install build-essential patch
  yes Y | sudo apt-get install ruby-dev zlib1g-dev
  yes Y | sudo apt-get install ruby1.8-dev ruby1.8 ri1.8 rdoc1.8 irb1.8
  yes Y | sudo apt-get install libreadline-ruby1.8 libruby1.8 libopenssl-ruby
  yes Y | sudo apt-get install libxslt-dev libxml2-dev zlib1g-dev
  sudo gem update
architect:
  - LeanderK
  - jundl77
decrypt:
  settings.xml: "repo/settings.xml.asc"
  pubring.gpg: "repo/pubring.gpg.asc"
  secring.gpg: "repo/secring.gpg.asc"
docker:
  image: "teamed/docker-java-8"
addons:
    apt:
      packages:
        - libmagic1
        - libmagic-dev
release:
  commanders:
      - LeanderK
      - jundl77
  script: |-
    sudo gem install --no-ri --no-rdoc pdd
    sudo gem install est
    sudo gem install pdd
    sudo gem install nokogiri
    mvn versions:set "-DnewVersion=${tag//\'}"
    git commit -am "${tag//\'}"
    mvn -Dmaven.test.skip=true clean deploy --settings /home/r/settings.xml
