// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server-protobuf/app_list.proto

package org.intellimate.server.proto;

public interface AppListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:intellimate.AppList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .intellimate.App apps = 1;</code>
   */
  java.util.List<org.intellimate.server.proto.App> 
      getAppsList();
  /**
   * <code>repeated .intellimate.App apps = 1;</code>
   */
  org.intellimate.server.proto.App getApps(int index);
  /**
   * <code>repeated .intellimate.App apps = 1;</code>
   */
  int getAppsCount();
  /**
   * <code>repeated .intellimate.App apps = 1;</code>
   */
  java.util.List<? extends org.intellimate.server.proto.AppOrBuilder> 
      getAppsOrBuilderList();
  /**
   * <code>repeated .intellimate.App apps = 1;</code>
   */
  org.intellimate.server.proto.AppOrBuilder getAppsOrBuilder(
      int index);
}
