// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server-protobuf/app_list.proto

package org.intellimate.server.proto;

/**
 * Protobuf type {@code intellimate.AppList}
 */
public  final class AppList extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:intellimate.AppList)
    AppListOrBuilder {
  // Use AppList.newBuilder() to construct.
  private AppList(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private AppList() {
    apps_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private AppList(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              apps_ = new java.util.ArrayList<org.intellimate.server.proto.App>();
              mutable_bitField0_ |= 0x00000001;
            }
            apps_.add(input.readMessage(org.intellimate.server.proto.App.parser(), extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw new RuntimeException(e.setUnfinishedMessage(this));
    } catch (java.io.IOException e) {
      throw new RuntimeException(
          new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this));
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        apps_ = java.util.Collections.unmodifiableList(apps_);
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.intellimate.server.proto.AppListOuterClass.internal_static_intellimate_AppList_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.intellimate.server.proto.AppListOuterClass.internal_static_intellimate_AppList_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.intellimate.server.proto.AppList.class, org.intellimate.server.proto.AppList.Builder.class);
  }

  public static final int APPS_FIELD_NUMBER = 1;
  private java.util.List<org.intellimate.server.proto.App> apps_;
  /**
   * <code>repeated .intellimate.App apps = 1;</code>
   */
  public java.util.List<org.intellimate.server.proto.App> getAppsList() {
    return apps_;
  }
  /**
   * <code>repeated .intellimate.App apps = 1;</code>
   */
  public java.util.List<? extends org.intellimate.server.proto.AppOrBuilder> 
      getAppsOrBuilderList() {
    return apps_;
  }
  /**
   * <code>repeated .intellimate.App apps = 1;</code>
   */
  public int getAppsCount() {
    return apps_.size();
  }
  /**
   * <code>repeated .intellimate.App apps = 1;</code>
   */
  public org.intellimate.server.proto.App getApps(int index) {
    return apps_.get(index);
  }
  /**
   * <code>repeated .intellimate.App apps = 1;</code>
   */
  public org.intellimate.server.proto.AppOrBuilder getAppsOrBuilder(
      int index) {
    return apps_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < apps_.size(); i++) {
      output.writeMessage(1, apps_.get(i));
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < apps_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, apps_.get(i));
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  public static org.intellimate.server.proto.AppList parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.intellimate.server.proto.AppList parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.intellimate.server.proto.AppList parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.intellimate.server.proto.AppList parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.intellimate.server.proto.AppList parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static org.intellimate.server.proto.AppList parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static org.intellimate.server.proto.AppList parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static org.intellimate.server.proto.AppList parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static org.intellimate.server.proto.AppList parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static org.intellimate.server.proto.AppList parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.intellimate.server.proto.AppList prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code intellimate.AppList}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:intellimate.AppList)
      org.intellimate.server.proto.AppListOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.intellimate.server.proto.AppListOuterClass.internal_static_intellimate_AppList_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.intellimate.server.proto.AppListOuterClass.internal_static_intellimate_AppList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.intellimate.server.proto.AppList.class, org.intellimate.server.proto.AppList.Builder.class);
    }

    // Construct using org.intellimate.server.proto.AppList.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        getAppsFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      if (appsBuilder_ == null) {
        apps_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        appsBuilder_.clear();
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.intellimate.server.proto.AppListOuterClass.internal_static_intellimate_AppList_descriptor;
    }

    public org.intellimate.server.proto.AppList getDefaultInstanceForType() {
      return org.intellimate.server.proto.AppList.getDefaultInstance();
    }

    public org.intellimate.server.proto.AppList build() {
      org.intellimate.server.proto.AppList result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public org.intellimate.server.proto.AppList buildPartial() {
      org.intellimate.server.proto.AppList result = new org.intellimate.server.proto.AppList(this);
      int from_bitField0_ = bitField0_;
      if (appsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          apps_ = java.util.Collections.unmodifiableList(apps_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.apps_ = apps_;
      } else {
        result.apps_ = appsBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.intellimate.server.proto.AppList) {
        return mergeFrom((org.intellimate.server.proto.AppList)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.intellimate.server.proto.AppList other) {
      if (other == org.intellimate.server.proto.AppList.getDefaultInstance()) return this;
      if (appsBuilder_ == null) {
        if (!other.apps_.isEmpty()) {
          if (apps_.isEmpty()) {
            apps_ = other.apps_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureAppsIsMutable();
            apps_.addAll(other.apps_);
          }
          onChanged();
        }
      } else {
        if (!other.apps_.isEmpty()) {
          if (appsBuilder_.isEmpty()) {
            appsBuilder_.dispose();
            appsBuilder_ = null;
            apps_ = other.apps_;
            bitField0_ = (bitField0_ & ~0x00000001);
            appsBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getAppsFieldBuilder() : null;
          } else {
            appsBuilder_.addAllMessages(other.apps_);
          }
        }
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.intellimate.server.proto.AppList parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.intellimate.server.proto.AppList) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<org.intellimate.server.proto.App> apps_ =
      java.util.Collections.emptyList();
    private void ensureAppsIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        apps_ = new java.util.ArrayList<org.intellimate.server.proto.App>(apps_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        org.intellimate.server.proto.App, org.intellimate.server.proto.App.Builder, org.intellimate.server.proto.AppOrBuilder> appsBuilder_;

    /**
     * <code>repeated .intellimate.App apps = 1;</code>
     */
    public java.util.List<org.intellimate.server.proto.App> getAppsList() {
      if (appsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(apps_);
      } else {
        return appsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .intellimate.App apps = 1;</code>
     */
    public int getAppsCount() {
      if (appsBuilder_ == null) {
        return apps_.size();
      } else {
        return appsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .intellimate.App apps = 1;</code>
     */
    public org.intellimate.server.proto.App getApps(int index) {
      if (appsBuilder_ == null) {
        return apps_.get(index);
      } else {
        return appsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .intellimate.App apps = 1;</code>
     */
    public Builder setApps(
        int index, org.intellimate.server.proto.App value) {
      if (appsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAppsIsMutable();
        apps_.set(index, value);
        onChanged();
      } else {
        appsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .intellimate.App apps = 1;</code>
     */
    public Builder setApps(
        int index, org.intellimate.server.proto.App.Builder builderForValue) {
      if (appsBuilder_ == null) {
        ensureAppsIsMutable();
        apps_.set(index, builderForValue.build());
        onChanged();
      } else {
        appsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .intellimate.App apps = 1;</code>
     */
    public Builder addApps(org.intellimate.server.proto.App value) {
      if (appsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAppsIsMutable();
        apps_.add(value);
        onChanged();
      } else {
        appsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .intellimate.App apps = 1;</code>
     */
    public Builder addApps(
        int index, org.intellimate.server.proto.App value) {
      if (appsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAppsIsMutable();
        apps_.add(index, value);
        onChanged();
      } else {
        appsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .intellimate.App apps = 1;</code>
     */
    public Builder addApps(
        org.intellimate.server.proto.App.Builder builderForValue) {
      if (appsBuilder_ == null) {
        ensureAppsIsMutable();
        apps_.add(builderForValue.build());
        onChanged();
      } else {
        appsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .intellimate.App apps = 1;</code>
     */
    public Builder addApps(
        int index, org.intellimate.server.proto.App.Builder builderForValue) {
      if (appsBuilder_ == null) {
        ensureAppsIsMutable();
        apps_.add(index, builderForValue.build());
        onChanged();
      } else {
        appsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .intellimate.App apps = 1;</code>
     */
    public Builder addAllApps(
        java.lang.Iterable<? extends org.intellimate.server.proto.App> values) {
      if (appsBuilder_ == null) {
        ensureAppsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, apps_);
        onChanged();
      } else {
        appsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .intellimate.App apps = 1;</code>
     */
    public Builder clearApps() {
      if (appsBuilder_ == null) {
        apps_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        appsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .intellimate.App apps = 1;</code>
     */
    public Builder removeApps(int index) {
      if (appsBuilder_ == null) {
        ensureAppsIsMutable();
        apps_.remove(index);
        onChanged();
      } else {
        appsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .intellimate.App apps = 1;</code>
     */
    public org.intellimate.server.proto.App.Builder getAppsBuilder(
        int index) {
      return getAppsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .intellimate.App apps = 1;</code>
     */
    public org.intellimate.server.proto.AppOrBuilder getAppsOrBuilder(
        int index) {
      if (appsBuilder_ == null) {
        return apps_.get(index);  } else {
        return appsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .intellimate.App apps = 1;</code>
     */
    public java.util.List<? extends org.intellimate.server.proto.AppOrBuilder> 
         getAppsOrBuilderList() {
      if (appsBuilder_ != null) {
        return appsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(apps_);
      }
    }
    /**
     * <code>repeated .intellimate.App apps = 1;</code>
     */
    public org.intellimate.server.proto.App.Builder addAppsBuilder() {
      return getAppsFieldBuilder().addBuilder(
          org.intellimate.server.proto.App.getDefaultInstance());
    }
    /**
     * <code>repeated .intellimate.App apps = 1;</code>
     */
    public org.intellimate.server.proto.App.Builder addAppsBuilder(
        int index) {
      return getAppsFieldBuilder().addBuilder(
          index, org.intellimate.server.proto.App.getDefaultInstance());
    }
    /**
     * <code>repeated .intellimate.App apps = 1;</code>
     */
    public java.util.List<org.intellimate.server.proto.App.Builder> 
         getAppsBuilderList() {
      return getAppsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        org.intellimate.server.proto.App, org.intellimate.server.proto.App.Builder, org.intellimate.server.proto.AppOrBuilder> 
        getAppsFieldBuilder() {
      if (appsBuilder_ == null) {
        appsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            org.intellimate.server.proto.App, org.intellimate.server.proto.App.Builder, org.intellimate.server.proto.AppOrBuilder>(
                apps_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        apps_ = null;
      }
      return appsBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:intellimate.AppList)
  }

  // @@protoc_insertion_point(class_scope:intellimate.AppList)
  private static final org.intellimate.server.proto.AppList DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.intellimate.server.proto.AppList();
  }

  public static org.intellimate.server.proto.AppList getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AppList>
      PARSER = new com.google.protobuf.AbstractParser<AppList>() {
    public AppList parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      try {
        return new AppList(input, extensionRegistry);
      } catch (RuntimeException e) {
        if (e.getCause() instanceof
            com.google.protobuf.InvalidProtocolBufferException) {
          throw (com.google.protobuf.InvalidProtocolBufferException)
              e.getCause();
        }
        throw e;
      }
    }
  };

  public static com.google.protobuf.Parser<AppList> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AppList> getParserForType() {
    return PARSER;
  }

  public org.intellimate.server.proto.AppList getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

