// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server-protobuf/app.proto

package org.intellimate.server.proto;

public interface AppOrBuilder extends
    // @@protoc_insertion_point(interface_extends:intellimate.App)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int32 id = 1;</code>
   */
  int getId();

  /**
   * <code>optional string name = 2;</code>
   */
  java.lang.String getName();
  /**
   * <code>optional string name = 2;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>optional string developer = 3;</code>
   */
  java.lang.String getDeveloper();
  /**
   * <code>optional string developer = 3;</code>
   */
  com.google.protobuf.ByteString
      getDeveloperBytes();

  /**
   * <code>optional string description = 4;</code>
   */
  java.lang.String getDescription();
  /**
   * <code>optional string description = 4;</code>
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();

  /**
   * <code>optional bool active = 5;</code>
   */
  boolean getActive();

  /**
   * <code>repeated string tags = 6;</code>
   */
  com.google.protobuf.ProtocolStringList
      getTagsList();
  /**
   * <code>repeated string tags = 6;</code>
   */
  int getTagsCount();
  /**
   * <code>repeated string tags = 6;</code>
   */
  java.lang.String getTags(int index);
  /**
   * <code>repeated string tags = 6;</code>
   */
  com.google.protobuf.ByteString
      getTagsBytes(int index);

  /**
   * <code>repeated .intellimate.App.AppVersion versions = 7;</code>
   */
  java.util.List<org.intellimate.server.proto.App.AppVersion> 
      getVersionsList();
  /**
   * <code>repeated .intellimate.App.AppVersion versions = 7;</code>
   */
  org.intellimate.server.proto.App.AppVersion getVersions(int index);
  /**
   * <code>repeated .intellimate.App.AppVersion versions = 7;</code>
   */
  int getVersionsCount();
  /**
   * <code>repeated .intellimate.App.AppVersion versions = 7;</code>
   */
  java.util.List<? extends org.intellimate.server.proto.App.AppVersionOrBuilder> 
      getVersionsOrBuilderList();
  /**
   * <code>repeated .intellimate.App.AppVersion versions = 7;</code>
   */
  org.intellimate.server.proto.App.AppVersionOrBuilder getVersionsOrBuilder(
      int index);
}
