// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server-protobuf/error_response.proto

package org.intellimate.server.proto;

public interface ErrorResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:intellimate.ErrorResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string code = 1;</code>
   */
  java.lang.String getCode();
  /**
   * <code>optional string code = 1;</code>
   */
  com.google.protobuf.ByteString
      getCodeBytes();

  /**
   * <code>optional string detail = 2;</code>
   */
  java.lang.String getDetail();
  /**
   * <code>optional string detail = 2;</code>
   */
  com.google.protobuf.ByteString
      getDetailBytes();
}
