// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server-protobuf/error_response.proto

package org.intellimate.server.proto;

public final class ErrorResponseOuterClass {
  private ErrorResponseOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_intellimate_ErrorResponse_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_intellimate_ErrorResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n$server-protobuf/error_response.proto\022\013" +
      "intellimate\"-\n\rErrorResponse\022\014\n\004code\030\001 \001" +
      "(\t\022\016\n\006detail\030\002 \001(\tB \n\034org.intellimate.se" +
      "rver.protoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_intellimate_ErrorResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_intellimate_ErrorResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_intellimate_ErrorResponse_descriptor,
        new java.lang.String[] { "Code", "Detail", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
