// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server-protobuf/izou_app_list.proto

package org.intellimate.server.proto;

public interface IzouAppListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:intellimate.IzouAppList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .intellimate.App selected = 1;</code>
   */
  java.util.List<org.intellimate.server.proto.App> 
      getSelectedList();
  /**
   * <code>repeated .intellimate.App selected = 1;</code>
   */
  org.intellimate.server.proto.App getSelected(int index);
  /**
   * <code>repeated .intellimate.App selected = 1;</code>
   */
  int getSelectedCount();
  /**
   * <code>repeated .intellimate.App selected = 1;</code>
   */
  java.util.List<? extends org.intellimate.server.proto.AppOrBuilder> 
      getSelectedOrBuilderList();
  /**
   * <code>repeated .intellimate.App selected = 1;</code>
   */
  org.intellimate.server.proto.AppOrBuilder getSelectedOrBuilder(
      int index);

  /**
   * <code>repeated .intellimate.App installed = 2;</code>
   */
  java.util.List<org.intellimate.server.proto.App> 
      getInstalledList();
  /**
   * <code>repeated .intellimate.App installed = 2;</code>
   */
  org.intellimate.server.proto.App getInstalled(int index);
  /**
   * <code>repeated .intellimate.App installed = 2;</code>
   */
  int getInstalledCount();
  /**
   * <code>repeated .intellimate.App installed = 2;</code>
   */
  java.util.List<? extends org.intellimate.server.proto.AppOrBuilder> 
      getInstalledOrBuilderList();
  /**
   * <code>repeated .intellimate.App installed = 2;</code>
   */
  org.intellimate.server.proto.AppOrBuilder getInstalledOrBuilder(
      int index);

  /**
   * <code>repeated .intellimate.App to_delete = 3;</code>
   */
  java.util.List<org.intellimate.server.proto.App> 
      getToDeleteList();
  /**
   * <code>repeated .intellimate.App to_delete = 3;</code>
   */
  org.intellimate.server.proto.App getToDelete(int index);
  /**
   * <code>repeated .intellimate.App to_delete = 3;</code>
   */
  int getToDeleteCount();
  /**
   * <code>repeated .intellimate.App to_delete = 3;</code>
   */
  java.util.List<? extends org.intellimate.server.proto.AppOrBuilder> 
      getToDeleteOrBuilderList();
  /**
   * <code>repeated .intellimate.App to_delete = 3;</code>
   */
  org.intellimate.server.proto.AppOrBuilder getToDeleteOrBuilder(
      int index);

  /**
   * <code>repeated .intellimate.App to_install = 4;</code>
   */
  java.util.List<org.intellimate.server.proto.App> 
      getToInstallList();
  /**
   * <code>repeated .intellimate.App to_install = 4;</code>
   */
  org.intellimate.server.proto.App getToInstall(int index);
  /**
   * <code>repeated .intellimate.App to_install = 4;</code>
   */
  int getToInstallCount();
  /**
   * <code>repeated .intellimate.App to_install = 4;</code>
   */
  java.util.List<? extends org.intellimate.server.proto.AppOrBuilder> 
      getToInstallOrBuilderList();
  /**
   * <code>repeated .intellimate.App to_install = 4;</code>
   */
  org.intellimate.server.proto.AppOrBuilder getToInstallOrBuilder(
      int index);

  /**
   * <code>repeated .intellimate.App to_install_downloaded = 5;</code>
   */
  java.util.List<org.intellimate.server.proto.App> 
      getToInstallDownloadedList();
  /**
   * <code>repeated .intellimate.App to_install_downloaded = 5;</code>
   */
  org.intellimate.server.proto.App getToInstallDownloaded(int index);
  /**
   * <code>repeated .intellimate.App to_install_downloaded = 5;</code>
   */
  int getToInstallDownloadedCount();
  /**
   * <code>repeated .intellimate.App to_install_downloaded = 5;</code>
   */
  java.util.List<? extends org.intellimate.server.proto.AppOrBuilder> 
      getToInstallDownloadedOrBuilderList();
  /**
   * <code>repeated .intellimate.App to_install_downloaded = 5;</code>
   */
  org.intellimate.server.proto.AppOrBuilder getToInstallDownloadedOrBuilder(
      int index);
}
