// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server-protobuf/izou.proto

package org.intellimate.server.proto;

public interface IzouOrBuilder extends
    // @@protoc_insertion_point(interface_extends:intellimate.Izou)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int32 id = 1;</code>
   */
  int getId();

  /**
   * <code>optional string version = 2;</code>
   */
  java.lang.String getVersion();
  /**
   * <code>optional string version = 2;</code>
   */
  com.google.protobuf.ByteString
      getVersionBytes();

  /**
   * <code>optional string download_link = 3;</code>
   */
  java.lang.String getDownloadLink();
  /**
   * <code>optional string download_link = 3;</code>
   */
  com.google.protobuf.ByteString
      getDownloadLinkBytes();
}
