// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server-protobuf/izou_instance_status.proto

package org.intellimate.server.proto;

public interface IzouInstanceStatusOrBuilder extends
    // @@protoc_insertion_point(interface_extends:intellimate.IzouInstanceStatus)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional .intellimate.IzouInstanceStatus.Status status = 1;</code>
   */
  int getStatusValue();
  /**
   * <code>optional .intellimate.IzouInstanceStatus.Status status = 1;</code>
   */
  org.intellimate.server.proto.IzouInstanceStatus.Status getStatus();
}
