// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server-protobuf/izou_instance_list.proto

package org.intellimate.server.proto;

/**
 * Protobuf type {@code intellimate.IzouInstanceList}
 */
public  final class IzouInstanceList extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:intellimate.IzouInstanceList)
    IzouInstanceListOrBuilder {
  // Use IzouInstanceList.newBuilder() to construct.
  private IzouInstanceList(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private IzouInstanceList() {
    instances_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private IzouInstanceList(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              instances_ = new java.util.ArrayList<org.intellimate.server.proto.IzouInstance>();
              mutable_bitField0_ |= 0x00000001;
            }
            instances_.add(input.readMessage(org.intellimate.server.proto.IzouInstance.parser(), extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        instances_ = java.util.Collections.unmodifiableList(instances_);
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.intellimate.server.proto.IzouInstanceListOuterClass.internal_static_intellimate_IzouInstanceList_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.intellimate.server.proto.IzouInstanceListOuterClass.internal_static_intellimate_IzouInstanceList_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.intellimate.server.proto.IzouInstanceList.class, org.intellimate.server.proto.IzouInstanceList.Builder.class);
  }

  public static final int INSTANCES_FIELD_NUMBER = 1;
  private java.util.List<org.intellimate.server.proto.IzouInstance> instances_;
  /**
   * <code>repeated .intellimate.IzouInstance instances = 1;</code>
   */
  public java.util.List<org.intellimate.server.proto.IzouInstance> getInstancesList() {
    return instances_;
  }
  /**
   * <code>repeated .intellimate.IzouInstance instances = 1;</code>
   */
  public java.util.List<? extends org.intellimate.server.proto.IzouInstanceOrBuilder> 
      getInstancesOrBuilderList() {
    return instances_;
  }
  /**
   * <code>repeated .intellimate.IzouInstance instances = 1;</code>
   */
  public int getInstancesCount() {
    return instances_.size();
  }
  /**
   * <code>repeated .intellimate.IzouInstance instances = 1;</code>
   */
  public org.intellimate.server.proto.IzouInstance getInstances(int index) {
    return instances_.get(index);
  }
  /**
   * <code>repeated .intellimate.IzouInstance instances = 1;</code>
   */
  public org.intellimate.server.proto.IzouInstanceOrBuilder getInstancesOrBuilder(
      int index) {
    return instances_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < instances_.size(); i++) {
      output.writeMessage(1, instances_.get(i));
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < instances_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, instances_.get(i));
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  public static org.intellimate.server.proto.IzouInstanceList parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.intellimate.server.proto.IzouInstanceList parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.intellimate.server.proto.IzouInstanceList parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.intellimate.server.proto.IzouInstanceList parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.intellimate.server.proto.IzouInstanceList parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static org.intellimate.server.proto.IzouInstanceList parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.intellimate.server.proto.IzouInstanceList parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.intellimate.server.proto.IzouInstanceList parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.intellimate.server.proto.IzouInstanceList parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static org.intellimate.server.proto.IzouInstanceList parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.intellimate.server.proto.IzouInstanceList prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code intellimate.IzouInstanceList}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:intellimate.IzouInstanceList)
      org.intellimate.server.proto.IzouInstanceListOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.intellimate.server.proto.IzouInstanceListOuterClass.internal_static_intellimate_IzouInstanceList_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.intellimate.server.proto.IzouInstanceListOuterClass.internal_static_intellimate_IzouInstanceList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.intellimate.server.proto.IzouInstanceList.class, org.intellimate.server.proto.IzouInstanceList.Builder.class);
    }

    // Construct using org.intellimate.server.proto.IzouInstanceList.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        getInstancesFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      if (instancesBuilder_ == null) {
        instances_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        instancesBuilder_.clear();
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.intellimate.server.proto.IzouInstanceListOuterClass.internal_static_intellimate_IzouInstanceList_descriptor;
    }

    public org.intellimate.server.proto.IzouInstanceList getDefaultInstanceForType() {
      return org.intellimate.server.proto.IzouInstanceList.getDefaultInstance();
    }

    public org.intellimate.server.proto.IzouInstanceList build() {
      org.intellimate.server.proto.IzouInstanceList result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public org.intellimate.server.proto.IzouInstanceList buildPartial() {
      org.intellimate.server.proto.IzouInstanceList result = new org.intellimate.server.proto.IzouInstanceList(this);
      int from_bitField0_ = bitField0_;
      if (instancesBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          instances_ = java.util.Collections.unmodifiableList(instances_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.instances_ = instances_;
      } else {
        result.instances_ = instancesBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.intellimate.server.proto.IzouInstanceList) {
        return mergeFrom((org.intellimate.server.proto.IzouInstanceList)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.intellimate.server.proto.IzouInstanceList other) {
      if (other == org.intellimate.server.proto.IzouInstanceList.getDefaultInstance()) return this;
      if (instancesBuilder_ == null) {
        if (!other.instances_.isEmpty()) {
          if (instances_.isEmpty()) {
            instances_ = other.instances_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureInstancesIsMutable();
            instances_.addAll(other.instances_);
          }
          onChanged();
        }
      } else {
        if (!other.instances_.isEmpty()) {
          if (instancesBuilder_.isEmpty()) {
            instancesBuilder_.dispose();
            instancesBuilder_ = null;
            instances_ = other.instances_;
            bitField0_ = (bitField0_ & ~0x00000001);
            instancesBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getInstancesFieldBuilder() : null;
          } else {
            instancesBuilder_.addAllMessages(other.instances_);
          }
        }
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.intellimate.server.proto.IzouInstanceList parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.intellimate.server.proto.IzouInstanceList) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<org.intellimate.server.proto.IzouInstance> instances_ =
      java.util.Collections.emptyList();
    private void ensureInstancesIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        instances_ = new java.util.ArrayList<org.intellimate.server.proto.IzouInstance>(instances_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        org.intellimate.server.proto.IzouInstance, org.intellimate.server.proto.IzouInstance.Builder, org.intellimate.server.proto.IzouInstanceOrBuilder> instancesBuilder_;

    /**
     * <code>repeated .intellimate.IzouInstance instances = 1;</code>
     */
    public java.util.List<org.intellimate.server.proto.IzouInstance> getInstancesList() {
      if (instancesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(instances_);
      } else {
        return instancesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .intellimate.IzouInstance instances = 1;</code>
     */
    public int getInstancesCount() {
      if (instancesBuilder_ == null) {
        return instances_.size();
      } else {
        return instancesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .intellimate.IzouInstance instances = 1;</code>
     */
    public org.intellimate.server.proto.IzouInstance getInstances(int index) {
      if (instancesBuilder_ == null) {
        return instances_.get(index);
      } else {
        return instancesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .intellimate.IzouInstance instances = 1;</code>
     */
    public Builder setInstances(
        int index, org.intellimate.server.proto.IzouInstance value) {
      if (instancesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureInstancesIsMutable();
        instances_.set(index, value);
        onChanged();
      } else {
        instancesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .intellimate.IzouInstance instances = 1;</code>
     */
    public Builder setInstances(
        int index, org.intellimate.server.proto.IzouInstance.Builder builderForValue) {
      if (instancesBuilder_ == null) {
        ensureInstancesIsMutable();
        instances_.set(index, builderForValue.build());
        onChanged();
      } else {
        instancesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .intellimate.IzouInstance instances = 1;</code>
     */
    public Builder addInstances(org.intellimate.server.proto.IzouInstance value) {
      if (instancesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureInstancesIsMutable();
        instances_.add(value);
        onChanged();
      } else {
        instancesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .intellimate.IzouInstance instances = 1;</code>
     */
    public Builder addInstances(
        int index, org.intellimate.server.proto.IzouInstance value) {
      if (instancesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureInstancesIsMutable();
        instances_.add(index, value);
        onChanged();
      } else {
        instancesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .intellimate.IzouInstance instances = 1;</code>
     */
    public Builder addInstances(
        org.intellimate.server.proto.IzouInstance.Builder builderForValue) {
      if (instancesBuilder_ == null) {
        ensureInstancesIsMutable();
        instances_.add(builderForValue.build());
        onChanged();
      } else {
        instancesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .intellimate.IzouInstance instances = 1;</code>
     */
    public Builder addInstances(
        int index, org.intellimate.server.proto.IzouInstance.Builder builderForValue) {
      if (instancesBuilder_ == null) {
        ensureInstancesIsMutable();
        instances_.add(index, builderForValue.build());
        onChanged();
      } else {
        instancesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .intellimate.IzouInstance instances = 1;</code>
     */
    public Builder addAllInstances(
        java.lang.Iterable<? extends org.intellimate.server.proto.IzouInstance> values) {
      if (instancesBuilder_ == null) {
        ensureInstancesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, instances_);
        onChanged();
      } else {
        instancesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .intellimate.IzouInstance instances = 1;</code>
     */
    public Builder clearInstances() {
      if (instancesBuilder_ == null) {
        instances_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        instancesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .intellimate.IzouInstance instances = 1;</code>
     */
    public Builder removeInstances(int index) {
      if (instancesBuilder_ == null) {
        ensureInstancesIsMutable();
        instances_.remove(index);
        onChanged();
      } else {
        instancesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .intellimate.IzouInstance instances = 1;</code>
     */
    public org.intellimate.server.proto.IzouInstance.Builder getInstancesBuilder(
        int index) {
      return getInstancesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .intellimate.IzouInstance instances = 1;</code>
     */
    public org.intellimate.server.proto.IzouInstanceOrBuilder getInstancesOrBuilder(
        int index) {
      if (instancesBuilder_ == null) {
        return instances_.get(index);  } else {
        return instancesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .intellimate.IzouInstance instances = 1;</code>
     */
    public java.util.List<? extends org.intellimate.server.proto.IzouInstanceOrBuilder> 
         getInstancesOrBuilderList() {
      if (instancesBuilder_ != null) {
        return instancesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(instances_);
      }
    }
    /**
     * <code>repeated .intellimate.IzouInstance instances = 1;</code>
     */
    public org.intellimate.server.proto.IzouInstance.Builder addInstancesBuilder() {
      return getInstancesFieldBuilder().addBuilder(
          org.intellimate.server.proto.IzouInstance.getDefaultInstance());
    }
    /**
     * <code>repeated .intellimate.IzouInstance instances = 1;</code>
     */
    public org.intellimate.server.proto.IzouInstance.Builder addInstancesBuilder(
        int index) {
      return getInstancesFieldBuilder().addBuilder(
          index, org.intellimate.server.proto.IzouInstance.getDefaultInstance());
    }
    /**
     * <code>repeated .intellimate.IzouInstance instances = 1;</code>
     */
    public java.util.List<org.intellimate.server.proto.IzouInstance.Builder> 
         getInstancesBuilderList() {
      return getInstancesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        org.intellimate.server.proto.IzouInstance, org.intellimate.server.proto.IzouInstance.Builder, org.intellimate.server.proto.IzouInstanceOrBuilder> 
        getInstancesFieldBuilder() {
      if (instancesBuilder_ == null) {
        instancesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            org.intellimate.server.proto.IzouInstance, org.intellimate.server.proto.IzouInstance.Builder, org.intellimate.server.proto.IzouInstanceOrBuilder>(
                instances_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        instances_ = null;
      }
      return instancesBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:intellimate.IzouInstanceList)
  }

  // @@protoc_insertion_point(class_scope:intellimate.IzouInstanceList)
  private static final org.intellimate.server.proto.IzouInstanceList DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.intellimate.server.proto.IzouInstanceList();
  }

  public static org.intellimate.server.proto.IzouInstanceList getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<IzouInstanceList>
      PARSER = new com.google.protobuf.AbstractParser<IzouInstanceList>() {
    public IzouInstanceList parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new IzouInstanceList(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<IzouInstanceList> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<IzouInstanceList> getParserForType() {
    return PARSER;
  }

  public org.intellimate.server.proto.IzouInstanceList getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

