// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server-protobuf/izou_instance.proto

package org.intellimate.server.proto;

public interface IzouInstanceOrBuilder extends
    // @@protoc_insertion_point(interface_extends:intellimate.IzouInstance)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int32 id = 1;</code>
   */
  int getId();

  /**
   * <code>optional string name = 2;</code>
   */
  java.lang.String getName();
  /**
   * <code>optional string name = 2;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>optional string token = 3;</code>
   */
  java.lang.String getToken();
  /**
   * <code>optional string token = 3;</code>
   */
  com.google.protobuf.ByteString
      getTokenBytes();
}
