// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server-protobuf/izou_instance_list.proto

package org.intellimate.server.proto;

public interface IzouInstanceListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:intellimate.IzouInstanceList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .intellimate.IzouInstance instances = 1;</code>
   */
  java.util.List<org.intellimate.server.proto.IzouInstance> 
      getInstancesList();
  /**
   * <code>repeated .intellimate.IzouInstance instances = 1;</code>
   */
  org.intellimate.server.proto.IzouInstance getInstances(int index);
  /**
   * <code>repeated .intellimate.IzouInstance instances = 1;</code>
   */
  int getInstancesCount();
  /**
   * <code>repeated .intellimate.IzouInstance instances = 1;</code>
   */
  java.util.List<? extends org.intellimate.server.proto.IzouInstanceOrBuilder> 
      getInstancesOrBuilderList();
  /**
   * <code>repeated .intellimate.IzouInstance instances = 1;</code>
   */
  org.intellimate.server.proto.IzouInstanceOrBuilder getInstancesOrBuilder(
      int index);
}
