// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server-protobuf/socket_connection_response.proto

package org.intellimate.server.proto;

public interface SocketConnectionResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:intellimate.SocketConnectionResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int32 id = 1;</code>
   */
  int getId();
}
