// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server-protobuf/socket_connection.proto

package org.intellimate.server.proto;

public interface SocketConnectionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:intellimate.SocketConnection)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string token = 1;</code>
   */
  java.lang.String getToken();
  /**
   * <code>optional string token = 1;</code>
   */
  com.google.protobuf.ByteString
      getTokenBytes();
}
