// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server-protobuf/user_authentication.proto

package org.intellimate.server.proto;

public final class UserAuthenticationOuterClass {
  private UserAuthenticationOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_intellimate_UserAuthentication_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_intellimate_UserAuthentication_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n)server-protobuf/user_authentication.pr" +
      "oto\022\013intellimate\"/\n\022UserAuthentication\022\r" +
      "\n\005token\030\001 \001(\t\022\n\n\002id\030\002 \001(\005B \n\034org.intelli" +
      "mate.server.protoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_intellimate_UserAuthentication_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_intellimate_UserAuthentication_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_intellimate_UserAuthentication_descriptor,
        new java.lang.String[] { "Token", "Id", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
