// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server-protobuf/user_authentication.proto

package org.intellimate.server.proto;

public interface UserAuthenticationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:intellimate.UserAuthentication)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string token = 1;</code>
   */
  java.lang.String getToken();
  /**
   * <code>optional string token = 1;</code>
   */
  com.google.protobuf.ByteString
      getTokenBytes();

  /**
   * <code>optional int32 id = 2;</code>
   */
  int getId();
}
