package intellimate.izou.contentgenerator;

import intellimate.izou.system.Context;

/**
 * The ContentData Class holds all the Data generated by ContentGenerators and is then passed to the Output.
 */
public class ContentData<T> {
    private final String id;
    private T t;
    private static final class Lock { }
    private final Object lock = new Lock();
    private Context context;

    public ContentData (String id) {
        this.id = id;
    }

    public ContentData (String id, Context context) {
        this.id = id;
        this.context = context;
    }

    /**
     * Returns the ID of the ContentGenerator.
     *
     * @return a String containing the ID.
     */
    public String getId () {
        return id;
    }

    /**
     * Sets the Data.
     *
     * @param t an Object containing the Data.
     */
    public void setData (T t) {
        synchronized (lock) {
            this.t = t;
        }
    }

    /**
     * Gets the Data generated by the ContentGenerators.
     *
     * @return Object T containing the Data.
     */
    public T getData () {
        synchronized (lock) {
            return t;
        }
    }
}
